# Generated by Django 4.0.4 on 2022-05-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sili', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='details',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='lname',
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
